version: '3'
services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb_local
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1003
