server:
  servlet:
    context-path: /movies-info-service
spring:
  config:
    activate:
      on-profile:
        - prod
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local
