spring:
  profiles:
    active: local
---
server:
  servlet:
    context-path: /movies-info-service
spring:
  config:
    activate:
      on-profile:
        - local
  data:
    mongodb:
      movies:
        database: movie_info_db
        uri: mongodb://localhost:27017
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration,org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration

---
server:
  servlet:
    context-path: /movies-info-service
spring:
  config:
    activate:
      on-profile:
        - non-prod
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local
